### ISSUE TITLE
Move to tapjs org?

### ISSUE THREAD

**Issue by jamestalmage** [tapjs/clean-yaml-object#1]
@isaacs

Another module extracted from `node-tap`.
- Add it to `tapjs` org?
- PR for `node-tap`?

I think I see one or two more modules worth extracting from `node-tap`. Do you want to me to continue publishing under my own account first, then moving it in to the org? Or is it OK for me to just create new repos within the org from the start? The latter would save me a little time changing over CI badges, updating package.json, etc - but it's not a big deal.

**Comment by isaacs** [comment]
Yes, yes, no, yes, respectively :)

**Comment by jamestalmage** [comment]
Done. Thanks!
