### ISSUE TITLE
RangeError: Invalid array length handling array of floats

### ISSUE THREAD

**Issue by bdentino** [tapjs/clean-yaml-object#7]
The following code fails with a RangeError exception when `object` is an array of floating point numbers:

**index.js#L43**

```
        // Fill in any holes.  This means we lose expandos,
        // but we were gonna lose those anyway.
        if (isArray) {
            object = Array.apply(null, object)
        }
```

**Comment by bdentino** [comment]
I should clarify. It fails when `object` is a **_single-element**_ array containing a floating point number. 

example:
`node -e 'Array.apply(null, [1.5])'`

**Comment by yanick** [comment]
Just want to say I got bit by that bug. Would be awesome if you could release a new version with the fix. :-)
